add * node-telegram-bot-api package * its types * npm start script * strictNullChecks = false cause of "index.ts:17:18 - error TS2531: Object is possibly 'null'." * code snipped for index.ts